pipeline {
    agent any

    environment {
        TERRAFORM_DIR = '.' 
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning the repository...'
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                echo 'Initializing Terraform...'
                sh """
                cd $TERRAFORM_DIR
                terraform init
                """
            }
        }

        stage('Terraform Plan') {
            steps {
                echo 'Generating Terraform Plan...'
                sh """
                cd $TERRAFORM_DIR
                terraform plan -out=tfplan
                """
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    echo 'Applying Terraform Changes...'
                    sh """
                    cd $TERRAFORM_DIR
                    terraform apply -auto-approve tfplan
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh """
            cd $TERRAFORM_DIR
            rm -f tfplan
            """
        }
        success {
            echo 'Terraform changes applied successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
