pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning the repository...'
                checkout scm
            }
        }
        stage('Prepare Environment') {
            steps {
                script {
                    sh 'mkdir -p ~/.ssh'
                    sh 'cp keys/id_rsa.pub ~/.ssh/id_rsa.pub'
                    sh 'chmod 600 ~/.ssh/id_rsa.pub'
                    sh 'echo "Public key copied to Jenkins environment."'
                }
            }
        }
        stage('Terraform Init') {
            steps {
                echo 'Initializing Terraform...'
                sh '''
                    export TF_VAR_public_key_path=$WORKSPACE/keys/id_rsa.pub
                    terraform init
                '''
            }
        }
        stage('Terraform Plan') {
            steps {
                echo 'Planning Terraform changes...'
                sh 'terraform plan'
            }
        }
        stage('Terraform Apply') {
            steps {
                echo 'Applying Terraform changes...'
                sh 'terraform apply -auto-approve'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -f tfplan'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
